name = "resourcinator"
compatibility_date = "Latest"
pages_build_output_dir = "./.svelte-kit/cloudflare"

# Environment variables (if needed)
[vars]
# Example: API_KEY = "your_api_key"

# KV Namespace binding for production environment
[[kv_namespaces]]
binding = "RESOURCES_KV"
id = "e8bcd3994b694e768a4d830857b79bca"
preview_id = "687fd45321d44b919873d5ad1b2a4705"
